/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import static GUI.pelanggan.stm;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author D2A
 */
public class pelanggan extends javax.swing.JFrame {
    public static Connection conn;
    public static Statement stm;
    DefaultTableModel tabmodel;
    ResultSet rs;
    
    public pelanggan() {
        initComponents();
        try {
           //Server Udinus
           /*conn=DriverManager.getConnection("jdbc:mysql://192.168.10.253/a112113379",
                    "a112113379","polke001");*/
           
           //Localhost
            conn=DriverManager.getConnection("jdbc:mysql://localhost/a112113379","root","");
            stm=conn.createStatement();
       } catch (SQLException ex) {
           Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
       }
        tampildata();
        
        atur_akses(false);
        atur_tombol(true,false,true,true,true,true);
    }
    
        private void atur_akses(boolean b) {
        xkodepel.setEnabled(b);
        xnamapel.setEnabled(b);
        xalamat.setEnabled(b);
        xkota.setEnabled(b);
    }
        
    private void atur_tombol(boolean b, boolean b0, boolean b1, boolean b2, boolean b3, boolean b4) {
        newButton.setEnabled(b);
        saveButton.setEnabled(b0);
        deleteButton.setEnabled(b1);
        updateButton.setEnabled(b2);
        printButton.setEnabled(b3);
        exitButton.setEnabled(b4);
    }
    
        private void tampildata() {
        tabmodel=new DefaultTableModel();
        tabmodel.addColumn("Kode");
        tabmodel.addColumn("Nama Pelanggan");
        tabmodel.addColumn("Alamat");
        tabmodel.addColumn("Kota");
        jTable1.setModel(tabmodel);
        String kueri="select * from pelanggan";
        try {
            stm=conn.createStatement();
            rs=stm.executeQuery(kueri);
            while (rs.next())
            {
                tabmodel.addRow(new Object[]{rs.getString("kode_pel"),
                    rs.getString("nama_pel"),
                    rs.getString("alamat_pel"),
                    rs.getString("kota_pel"),
                });
            }
        } catch (SQLException ex) {
            Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
           }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kodeLabel = new javax.swing.JLabel();
        xkodepel = new javax.swing.JTextField();
        xnamapel = new javax.swing.JTextField();
        xalamat = new javax.swing.JTextField();
        xkota = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        kotaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        newButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ENTRY DATA PELANGGAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, 34));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kodeLabel.setText("Kode Pelanggan");
        jPanel2.add(kodeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        xkodepel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xkodepelActionPerformed(evt);
            }
        });
        xkodepel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xkodepelKeyPressed(evt);
            }
        });
        jPanel2.add(xkodepel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 148, -1));

        xnamapel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                xnamapelFocusGained(evt);
            }
        });
        xnamapel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xnamapelKeyPressed(evt);
            }
        });
        jPanel2.add(xnamapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 148, -1));

        xalamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                xalamatKeyPressed(evt);
            }
        });
        jPanel2.add(xalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 148, -1));
        jPanel2.add(xkota, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 148, -1));

        namaLabel.setText("Nama Pelanggan");
        jPanel2.add(namaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        alamatLabel.setText("Alamat Pelanggan");
        jPanel2.add(alamatLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        kotaLabel.setText("Kota Pelanggan");
        jPanel2.add(kotaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        newButton.setText("New");
        newButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newButtonMouseClicked(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveButtonMouseClicked(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print");

        exitButton.setText("Exit");
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(printButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(newButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(printButton)
                    .addComponent(exitButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 520, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed

    private void xkodepelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xkodepelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xkodepelActionPerformed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        int pilih=JOptionPane.showConfirmDialog(null,
                "Yakin Keluar ?","Perhatian !",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (pilih==0)
        {
             System.exit(0);
        }
               // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonMouseClicked

    private void saveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveButtonMouseClicked
         // Membuat perintah SQL INSERT INTO
        String kueri2 = "insert into pelanggan values('" + xkodepel.getText() + "',"+
             "'" + xnamapel.getText() + "'," +
             "'" + xalamat.getText() + "'," +
             "'" + xkota.getText() + "')";

        try {
        // Menjalankan perintah SQL INSERT INTO
        stm = conn.createStatement();
        stm.executeUpdate(kueri2);
        // Menampilkan pesan sukses
        JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan ke database.");
        // Mengosongkan input fields
        xkodepel.setText("");
        xnamapel.setText("");
        xalamat.setText("");
        xkota.setText("");
        
        //Atur akses field dan button
        atur_akses(false);
        xkodepel.requestFocus();
        atur_tombol(true,false,true,true,true,true);
        
        // Memanggil method tampildata() untuk menampilkan data terbaru
        tampildata();
    } catch (SQLException ex) {
        Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat menambahkan data ke database.");
    }
        
    }//GEN-LAST:event_saveButtonMouseClicked

    private void xnamapelFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_xnamapelFocusGained
        if(xkodepel.getText().length()>12)
        {
            JOptionPane.showMessageDialog(null, "panjang kode tidak boleh lebih dari 6");
        }
    }//GEN-LAST:event_xnamapelFocusGained

    private void xkodepelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xkodepelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (xkodepel.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "kolom masih kosong");
            } else {
                xnamapel.requestFocus();
            }
        }
    }//GEN-LAST:event_xkodepelKeyPressed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        //Konfirmasi delete
        int pilih2 = JOptionPane.showConfirmDialog(null,
                "Yakin Hapus ?", "Delete !",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
            // Membuat perintah SQL DELETE
            String kueri3 = "delete from pelanggan where kode_pel = '" + xkodepel.getText() + "'";
            if (pilih2 == 0) {
            try {
                // Menjalankan perintah SQL DELETE
                stm = conn.createStatement();
                stm.executeUpdate(kueri3);
                // Menampilkan pesan sukses
                JOptionPane.showMessageDialog(null, "Data berhasil dihapus dari database.");
                // Mengosongkan input fields
                xkodepel.setText("");
                xnamapel.setText("");
                xalamat.setText("");
                xkota.setText("");
                //Atur akses field dan button
                atur_akses(false);
                // Memanggil method tampildata() untuk menampilkan data terbaru
                tampildata();
            } catch (SQLException ex) {
                Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_deleteButtonMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        xkodepel.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
        xnamapel.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 1));
        xalamat.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 2));
        xkota.setText((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3));
        
        //atur akses
        atur_akses(true);
        xkodepel.requestFocus();
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
       
        // Membuat perintah SQL UPDATE
        String kueri4 = "update pelanggan set nama_pel = '" + xnamapel.getText() + "',"
                + "alamat_pel = '" + xalamat.getText() + "',"
                + "kota_pel = '" + xkota.getText() + "' where kode_pel = '" + xkodepel.getText() + "'";
        try {
            // Menjalankan perintah SQL UPDATE
            stm = conn.createStatement();
            stm.executeUpdate(kueri4);
            // Menampilkan pesan sukses
            JOptionPane.showMessageDialog(null, "Data berhasil diupdate.");
            // Mengosongkan input fields
            xkodepel.setText("");
            xnamapel.setText("");
            xalamat.setText("");
            xkota.setText("");
            //Atur akses field dan button
            atur_akses(false);
            // Memanggil method tampildata() untuk menampilkan data terbaru
            tampildata();

        } catch (SQLException ex) {
            Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_updateButtonMouseClicked

    private void newButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newButtonMouseClicked
        atur_akses(true);
        xkodepel.requestFocus();
        atur_tombol(false,true,false,false,false,true);
    }//GEN-LAST:event_newButtonMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void xnamapelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xnamapelKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (xnamapel.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "kolom masih kosong");
            } else {
                xalamat.requestFocus();
            }
        }
    }//GEN-LAST:event_xnamapelKeyPressed

    private void xalamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_xalamatKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (xalamat.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "kolom masih kosong");
            } else {
                xkota.requestFocus();
            }
        }
    }//GEN-LAST:event_xalamatKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel kodeLabel;
    private javax.swing.JLabel kotaLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JButton newButton;
    private javax.swing.JButton printButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField xalamat;
    private javax.swing.JTextField xkodepel;
    private javax.swing.JTextField xkota;
    private javax.swing.JTextField xnamapel;
    // End of variables declaration//GEN-END:variables

}
